#ifndef __pcm_def_h__
#define __pcm_def_h__

/*
 * Auto generated by DE, please DO NOT modify this file directly.
 */

/* --- R0 Define --- */
#define R0_SC_26M_CK_OFF                      (1 << 0)
#define R0_SC_ARM_CK_OFF_PCM                  (1 << 1)
#define R0_SC_MEM_CK_OFF_PCM                  (1 << 2)
#define R0_SC_AXI_CK_OFF                      (1 << 3)
#define R0_SC_SMI_CK_OFF                      (1 << 4)
#define R0_SC_MD26M_CK_OFF                    (1 << 5)
#define R0_SC_ARMPLLOUT_OFF_PCM               (1 << 6)
#define R0_SC_MAINPLLOUT_OFF                  (1 << 7)
#define R0_SC_MPLL_OFF                        (1 << 8)
#define R0_SC_ARMPLL_OFF_PCM                  (1 << 9)
#define R0_SC_MAINPLL_OFF                     (1 << 10)
#define R0_SC_CKSQ0_OFF                       (1 << 11)
#define R0_SC_CKSQ1_OFF                       (1 << 12)
#define R0_SC_MPLL_S_OFF                      (1 << 13)
#define R0_SC_ARMDDS_OFF_PCM                  (1 << 14)
#define R0_SC_MAINDDS_OFF                     (1 << 15)
#define R0_SC_DR_GATE_RETRY_EN_PCM            (1 << 16)
#define R0_SC_DPY_MODE_SW_PCM                 (1 << 17)
#define R0_SC_DMSUS_OFF_PCM                   (1 << 18)
#define R0_SC_DPY_2ND_DLL_EN_PCM              (1 << 19)
#define R0_SC_DPY_DLL_EN_PCM                  (1 << 20)
#define R0_SC_DPY_DLL_CK_EN_PCM               (1 << 21)
#define R0_SC_DPY_VREF_EN_PCM                 (1 << 22)
#define R0_SC_PHYPLL_EN_PCM                   (1 << 23)
#define R0_SC_DDRPHY_FB_CK_EN_PCM             (1 << 24)
#define R0_SC_DR_SHU_EN_PCM                   (1 << 25)
#define R0_SC_PHYPLL_SHU_EN_PCM               (1 << 26)
#define R0_SC_PHYPLL2_SHU_EN_PCM              (1 << 27)
#define R0_SC_PHYPLL_MODE_SW_PCM              (1 << 28)
#define R0_SC_PHYPLL2_MODE_SW_PCM             (1 << 29)
#define R0_SC_DR_SHU_LEVEL_PCM0               (1 << 30)
#define R0_SC_DR_SHU_LEVEL_PCM1               (1 << 31)
/* --- R7 Define --- */
#define R7_PWRAP_SLEEP_REQ                    (1 << 0)
#define R7_EMI_CLK_OFF_REQ_PCM                (1 << 1)
#define R7_PCM_TOP_MAS_PAU_REQ                (1 << 2)
#define R7_SC_DR_SHORT_QUEUE_PCM              (1 << 3)
#define R7_PCM_CK_SEL0                        (1 << 4)
#define R7_PCM_CK_SEL1                        (1 << 5)
#define R7_SC_MD32_WAKEUP                     (1 << 6)
#define R7_FHC_PAUSE_ARM_PCM                  (1 << 7)
#define R7_SC_26M_CK_SEL                      (1 << 8)
#define R7_PCM_TIMER_SET                      (1 << 9)
#define R7_PCM_TIMER_CLR                      (1 << 10)
#define R7_SRCVOLTEN                          (1 << 11)
#define R7_CSYSPWRUPACK                       (1 << 12)
#define R7_PCM_IM_SLP_EN                      (1 << 13)
#define R7_SRCCLKENO0                         (1 << 14)
#define R7_SYSRST                             (1 << 15)
#define R7_MD_APSRC_ACK_0                     (1 << 16)
#define R7_CPU_SYS_TIMER_CLK_SEL              (1 << 17)
#define R7_SC_AXI_DCM_DIS                     (1 << 18)
#define R7_FHC_PAUSE_MAIN                     (1 << 19)
#define R7_FHC_PAUSE_MEM                      (1 << 20)
#define R7_SRCCLKENO1                         (1 << 21)
#define R7_PCM_WDT_KICK_P                     (1 << 22)
#define R7_PCM_TWAM_EVENT_CLR                 (1 << 23)
#define R7_WAKEUP_EXT_W_SEL                   (1 << 24)
#define R7_WAKEUP_EXT_R_SEL                   (1 << 25)
#define R7_PMIC_IRQ_REQ_EN                    (1 << 26)
#define R7_FHC_PAUSE_MPLL                     (1 << 27)
#define R7_FORCE_F26M_WAKE                    (1 << 28)
#define R7_FORCE_APSRC_WAKE                   (1 << 29)
#define R7_FORCE_INFRA_WAKE                   (1 << 30)
#define R7_FORCE_VRF18_WAKE                   (1 << 31)
/* --- R12 Define --- */
#define R12_PCM_TIMER                         (1 << 0)
#define R12_PMCU_WDT_EVENT_B                  (1 << 1)
#define R12_KP_IRQ_B                          (1 << 2)
#define R12_APWDT_EVENT_B                     (1 << 3)
#define R12_APXGPT1_EVENT_B                   (1 << 4)
#define R12_CONN2AP_SPM_WAKEUP_B              (1 << 5)
#define R12_EINT_EVENT_B                      (1 << 6)
#define R12_CONN_WDT_IRQ_B                    (1 << 7)
#define R12_CCIF0_EVENT_B                     (1 << 8)
#define R12_LOWBATTERY_IRQ_B                  (1 << 9)
#define R12_PMCU_SPM_IRQ_B                    (1 << 10)
#define R12_SCP_SPM_IRQ_B                     (1 << 11)
#define R12_SCP_WDT_EVENT_B                   (1 << 12)
#define R12_PCM_WDT_WAKEUP_B                  (1 << 13)
#define R12_USBX_CDSC_B                       (1 << 14)
#define R12_USBX_POWERDWN_B                   (1 << 15)
#define R12_C2K_WDT_IRQ_B                     (1 << 16)
#define R12_EINT_EVENT_SECURE_B               (1 << 17)
#define R12_CCIF1_EVENT_B                     (1 << 18)
#define R12_OTHERS_IRQ_B                      (1 << 19)
#define R12_AFE_IRQ_MCU_B                     (1 << 20)
#define R12_THERM_CTRL_EVENT_B                (1 << 21)
#define R12_SYS_CIRQ_IRQ_B                    (1 << 22)
#define R12_NOT_USED0                         (1 << 23)
#define R12_CSYSPWREQ_B                       (1 << 24)
#define R12_MD1_WDT_B                         (1 << 25)
#define R12_CLDMA_EVENT_B                     (1 << 26)
#define R12_SEJ_EVENT_B                       (1 << 27)
#define R12_ALL_MD32_WAKEUP_B                 (1 << 28)
#define R12_CPU_IRQ_B                         (1 << 29)
#define R12_ALL_SCP_WAKEUP_B                  (1 << 30)
#define R12_NOT_USED1                         (1 << 31)
/* --- R12ext Define --- */
#define R12EXT_F26M_WAKE                      (1 << 0)
#define R12EXT_F26M_SLEEP                     (1 << 1)
#define R12EXT_INFRA_WAKE                     (1 << 2)
#define R12EXT_INFRA_SLEEP                    (1 << 3)
#define R12EXT_APSRC_WAKE                     (1 << 4)
#define R12EXT_APSRC_SLEEP                    (1 << 5)
#define R12EXT_VRF18_WAKE                     (1 << 6)
#define R12EXT_VRF18_SLEEP                    (1 << 7)
#define R12EXT_DVFS_LEVEL0_STATE              (1 << 8)
#define R12EXT_DVFS_LEVEL1_STATE              (1 << 9)
#define R12EXT_DVFS_LEVEL2_STATE              (1 << 10)
#define R12EXT_DVFS_LEVEL3_STATE              (1 << 11)
#define R12EXT_DVFS_LEVEL4_STATE              (1 << 12)
#define R12EXT_SW_MAILBOX_STATE               (1 << 13)
#define R12EXT_PMCU_MAILBOX_STATE             (1 << 14)
#define R12EXT_DDREN_WAKE                     (1 << 15)
#define R12EXT_DDREN_SLEEP                    (1 << 16)
#define R12EXT_RESERVECKSEL3_WAKE             (1 << 17)
#define R12EXT_RESERVECKSEL3_SLEEP            (1 << 18)
#define R12EXT_RESERVECKSEL2_WAKE             (1 << 19)
#define R12EXT_RESERVECKSEL2_SLEEP            (1 << 20)
#define R12EXT_BIT21                          (1 << 21)
#define R12EXT_BIT22                          (1 << 22)
#define R12EXT_BIT23                          (1 << 23)
#define R12EXT_BIT24                          (1 << 24)
#define R12EXT_BIT25                          (1 << 25)
#define R12EXT_BIT26                          (1 << 26)
#define R12EXT_BIT27                          (1 << 27)
#define R12EXT_BIT28                          (1 << 28)
#define R12EXT_BIT29                          (1 << 29)
#define R12EXT_BIT30                          (1 << 30)
#define R12EXT_BIT31                          (1 << 31)
/* --- R13 Define --- */
#define R13_SRCCLKENI0                        (1 << 0)
#define R13_SRCCLKENI1                        (1 << 1)
#define R13_MD_SRCCLKENA_0                    (1 << 2)
#define R13_MD_APSRC_REQ_0                    (1 << 3)
#define R13_CONN_DDR_EN                       (1 << 4)
#define R13_MD_SRCCLKENA_1                    (1 << 5)
#define R13_MD32_SRCCLKENA                    (1 << 6)
#define R13_MD32_APSRC_REQ                    (1 << 7)
#define R13_MD1_STATE                         (1 << 8)
#define R13_MD2_STATE                         (1 << 9)
#define R13_MM_STATE                          (1 << 10)
#define R13_MD32_STATE                        (1 << 11)
#define R13_MD_DDR_EN_0                       (1 << 12)
#define R13_CONN_STATE                        (1 << 13)
#define R13_CONN_SRCCLKENA                    (1 << 14)
#define R13_CONN_APSRC_REQ                    (1 << 15)
#define R13_SLEEP_EVENT_STA                   (1 << 16)
#define R13_WAKE_EVENT_STA                    (1 << 17)
#define R13_SCP_STATE                         (1 << 18)
#define R13_CSYSPWRUPREQ                      (1 << 19)
#define R13_PWRAP_SLEEP_ACK                   (1 << 20)
#define R13_EMI_CLK_OFF_ACK_ALL               (1 << 21)
#define R13_TOP_MAS_PAU_ACK                   (1 << 22)
#define R13_SW_DMDRAMCSHU_ACK_ALL             (1 << 23)
#define R13_MD_APSRC_REQ_1                    (1 << 24)
#define R13_DR_SHORT_QUEUE_ACK_ALL            (1 << 25)
#define R13_SUBSYS_IDLE_SIGNALS0              (1 << 26)
#define R13_MD_DDR_EN_1                       (1 << 27)
#define R13_SCP_SRCCLKENA                     (1 << 28)
#define R13_SCP_APSRC_REQ                     (1 << 29)
#define R13_MD_VRF18_REQ_0                    (1 << 30)
#define R13_MD_VRF18_REQ_1                    (1 << 31)

enum SPM_WAKE_SRC_LIST {
	WAKE_SRC_R12_PCM_TIMER = (1 << 0),
	WAKE_SRC_R12_PMCU_WDT_EVENT_B = (1 << 1),
	WAKE_SRC_R12_KP_IRQ_B = (1 << 2),
	WAKE_SRC_R12_APWDT_EVENT_B = (1 << 3),
	WAKE_SRC_R12_APXGPT1_EVENT_B = (1 << 4),
	WAKE_SRC_R12_CONN2AP_SPM_WAKEUP_B = (1 << 5),
	WAKE_SRC_R12_EINT_EVENT_B = (1 << 6),
	WAKE_SRC_R12_CONN_WDT_IRQ_B = (1 << 7),
	WAKE_SRC_R12_CCIF0_EVENT_B = (1 << 8),
	WAKE_SRC_R12_LOWBATTERY_IRQ_B = (1 << 9),
	WAKE_SRC_R12_PMCU_SPM_IRQ_B = (1 << 10),
	WAKE_SRC_R12_SCP_SPM_IRQ_B = (1 << 11),
	WAKE_SRC_R12_SCP_WDT_EVENT_B = (1 << 12),
	WAKE_SRC_R12_PCM_WDT_WAKEUP_B = (1 << 13),
	WAKE_SRC_R12_USBX_CDSC_B = (1 << 14),
	WAKE_SRC_R12_USBX_POWERDWN_B = (1 << 15),
	WAKE_SRC_R12_C2K_WDT_IRQ_B = (1 << 16),
	WAKE_SRC_R12_EINT_EVENT_SECURE_B = (1 << 17),
	WAKE_SRC_R12_CCIF1_EVENT_B = (1 << 18),
	WAKE_SRC_R12_OTHERS_IRQ_B = (1 << 19),
	WAKE_SRC_R12_AFE_IRQ_MCU_B = (1 << 20),
	WAKE_SRC_R12_THERM_CTRL_EVENT_B = (1 << 21),
	WAKE_SRC_R12_SYS_CIRQ_IRQ_B = (1 << 22),
	WAKE_SRC_R12_NOT_USED0 = (1 << 23),
	WAKE_SRC_R12_CSYSPWREQ_B = (1 << 24),
	WAKE_SRC_R12_MD1_WDT_B = (1 << 25),
	WAKE_SRC_R12_CLDMA_EVENT_B = (1 << 26),
	WAKE_SRC_R12_SEJ_EVENT_B = (1 << 27),
	WAKE_SRC_R12_ALL_MD32_WAKEUP_B = (1 << 28),
	WAKE_SRC_R12_CPU_IRQ_B = (1 << 29),
	WAKE_SRC_R12_ALL_SCP_WAKEUP_B = (1 << 30),
	WAKE_SRC_R12_NOT_USED1 = (1 << 31)
};

#if 0
extern const char *wakesrc_str[32];
#endif

#endif /* __pcm_def_h__ */
