//MTK : PPC Tool 
//(DO NOT EDIT: machine generated header)
#ifndef PPC_APP_PARA_H
#define PPC_APP_PARA_H
#include "ppc_app_type.h"
#define PPC_TUNING_VERSION 0x5a33406b
#define ELE_NUM  3
unsigned int app_element[ELE_NUM] = {
  ELE_INPUT_0,
  ELE_MASTER_VOLUME_0,
  ELE_OUTPU_0,
};

#define PARA_NUM  6
APP_PARA_INFO app_para_info[PARA_NUM] = {
  {"PARA_INPUT_SAMPLE_RATE",ELE_INPUT_0,PARA_INPUT_SAMPLE_RATE,1},
  {"PARA_INPUT_SAMPLE_FORMAT",ELE_INPUT_0,PARA_INPUT_SAMPLE_FORMAT,1},
  {"PARA_INPUT_SUPPORT_CH",ELE_INPUT_0,PARA_INPUT_SUPPORT_CH,11},
  {"PARA_MASTERVOL_SET_GAIN",ELE_MASTER_VOLUME_0,PARA_MASTERVOL_SET_GAIN,1},
  {"PARA_MASTERVOL_SMOOTH_ORDER",ELE_MASTER_VOLUME_0,PARA_MASTERVOL_SMOOTH_ORDER,1},
  {"PARA_OUTPUT_CH_MODE",ELE_OUTPU_0,PARA_OUTPUT_CH_MODE,1},
};

#endif
