/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * MediaTek Inc. (C) 2014. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */


#ifndef _U_APP_DEF_H_
#define _U_APP_DEF_H_

#define CONFIG_SUPPORT_BUTTON_SOUND_APP 0

#define CONFIG_SUPPORT_DM_APP 1

#ifdef DLNA_SUPPORT
#define CONFIG_SUPPORT_DLNA_APP 1
#endif

#ifdef BT_AND_HFP_SUPPORT
#define CONFIG_SUPPORT_BT_APP 1
#ifdef CONSYS_WIFI_CHIP
#define CONFIG_SUPPORT_BT_HFP_APP  1
#endif /*CONSYS_WIFI_CHIP*/
#ifdef WIFI_CHIP_6630
#define CONFIG_SUPPORT_BT_HFP_APP  1
#endif /*WIFI_CHIP_6630*/
#ifdef WIFI_CHIP_7668
#define CONFIG_SUPPORT_BT_HFP_APP  1
#endif /*WIFI_CHIP_7668*/
#else
#define CONFIG_SUPPORT_BT_APP 0
#ifdef CONSYS_WIFI_CHIP
#define CONFIG_SUPPORT_BT_HFP_APP  0
#endif /*CONSYS_WIFI_CHIP*/
#ifdef WIFI_CHIP_6630
#define CONFIG_SUPPORT_BT_HFP_APP  0
#endif /*WIFI_CHIP_6630*/
#ifdef WIFI_CHIP_7668
#define CONFIG_SUPPORT_BT_HFP_APP  0
#endif /*WIFI_CHIP_7668*/


#endif /*BT_AND_HFP_SUPPORT*/

#ifdef CONSYS_ALGO_WENZHI
#define CONFIG_SUPPORT_ALGO_WENZHI 1
#endif

#define CONFIG_SUPPORT_OPEN_ALSA_VOLUME  0

#define	CONFIG_APP_SUPPORT_SMART_CONNECTION 1

#define CONFIG_SUPPORT_APPMAIN_RESTART 0

#endif /*_U_APP_DEF_H_*/
